language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs

script: ./b clean && ./b check

sudo: false

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.npm

